# -*- coding: utf-8 -*-
"""lab_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fPS2ygPiKtTpBZSwWUwpF1RSFzgohFuK
"""

from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

a=pd.read_csv("products-100 (1).csv")
a

data=a[["Price","Stock"]]
data

data.isnull().sum()

a.describe()

x=a[['Price']]
x

y=a['Stock']
y

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
accuracy=r2_score(y_test,y_pred)
print(accuracy*100)

# Remove the shadowed 'input' variable to restore the built-in input() function
# if 'input' in globals() and isinstance(globals()['input'], list):
#     del globals()['input']

run_time=int(input("enter your price:"))
price_input=[[run_time]]
print("stock:",model.predict(price_input))

import matplotlib.pyplot as plt
plt.scatter(x,y,color="red",label="data")
plt.plot(x_test,y_pred,color="blue",label="model")
plt.xlabel("PRICE")
plt.ylabel("STOCK ")
plt.legend()
plt.show()

from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import  LabelEncoder

# data=pd.read_csv("offers.csv")
# data

a=data.head(100)
a

a=pd.read_csv("products-100 (1).csv")
a

le= LabelEncoder()
a['Availability']=le.fit_transform(
    a['Availability']
)

x=a[['Internal ID','Price']]
y=a['Price']

x_train,x_test,y_train,y_test=train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

r2=r2_score(y_test,y_pred)
print("\n" + "=" * 40)
print("MODEL VALIDATION")
print("=" * 40)

print("R2 Score :", round(r2, 4))

print("\nIntercept")
print(round(model.intercept_, 2))
print("\nCoefficients")

for feature, coef in zip(x.columns, model.coef_):
  print(feature,":",round(coef,2))

import pandas as pd

# Get user inputs safely using valid variable names (no spaces)
internal_id = float(input("Enter internal ID: "))
price_val = float(input("Enter price: "))

# Create a DataFrame using the exact feature names the model was trained on
user_data = pd.DataFrame(
    [[internal_id, price_val]],
    columns=["Internal ID", "Price"]
)

# Make prediction
prediction = model.predict(user_data)

print("\n" + "=" * 40)
print("PREDICTION RESULT")
print("=" * 40)
print("Internal ID:", internal_id)
print("Price Input:", price_val)
print("Predicted Output:", round(prediction[0], 2))

from mpl_toolkits.mplot3d import Axes3D

fig=plt(figsize=(9,6))
ax=fig.add_subplot(111,projection="3d")
ax.scatter()

