# -*- coding: utf-8 -*-
"""lab_ds_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jCTmFDI2s2JTEW0B8MBx7jEjSFKMKa1m
"""

from scipy.stats import poisson
import numpy as np

# A website receives an average of 4 visitors per minute. What is the probability that exactly 2 visitors arrive in the next minute?
k=2
lam=4
ad=poisson.pmf(k,lam)
ad

c=np.arange(1,11)
c

data=poisson.pmf(c,lam)
data

import matplotlib.pyplot as plt
plt.bar(c,data)
plt.xlabel("value of c")
plt.ylabel("data")
plt.show()

import pandas as pd

data=pd.read_csv("support-tickets-100.csv")
data

mydata=data.head(50)
mydata

c=mydata.isnull().sum()
c

df=mydata.dropna()
df

import pandas as pd

e= {
    "Name": ["Anand", "Balu", "Ravi", "Anand"],
    "Age": [22, 21, None, 22],
    "Marks": [85, 90, 75, 85]
}

df = pd.DataFrame(e)

df["Age"] = df["Age"].fillna(df["Age"].median())
df = df.drop_duplicates()
print("\nCleaned Data:")
print(df)