# -*- coding: utf-8 -*-
"""log-reg,knn-lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ig8mmC5NygX_70FPrBvob9FkrHJm43pn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

data=pd.read_csv("price.csv")
data

a=data.dropna()
a

d=a[['Period','Data_value']]
d

print("\nmissing value")
print(d.isnull().sum())

d.drop_duplicates(inplace=True)

print("\nDataset Shape:", d.shape)

X=d[['Period']]
Y=d['Data_value']

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.20,
    random_state=42
)

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
# X_test=scaler.transform(X_test)

model = LogisticRegression(
    class_weight='balanced',
    random_state=42
)
model.fit(X_train, Y_train)

# y_pred = model.predict(X_test)

accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy:", accuracy*100)

plt.scatter(X,Y)
plt.show()

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import r2_score

da=pd.read_csv("enterprise-customers.csv")
da

x=da[['Number of Employees','Annual Revenue']]
x

y=da['Contract Value']
y

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

models=KNeighborsClassifier(n_neighbors=5)
models.fit(x_train,y_train)

Number_of_Employees = int(input("Enter Number of Employees: "))
Annual_Revenue = int(input("Enter Annual Revenue: "))
# print(models.predict([[Number_of_Employees, Annual_Revenue]]))
inputss=[[Number_of_Employees,Annual_Revenue]]
print(models.predict(inputss))

from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsRegressor

# Using Regressor instead of Classifier for continuous target 'Contract Value'
reg_model = KNeighborsRegressor(n_neighbors=5)
score = cross_val_score(reg_model, x, y, scoring='r2')
print("average R2 score:", score.mean())

from sklearn.naive_bayes import MultinomialNB

cd=da[['Payment Terms','Support Level']]
cd

